apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartdine-ingress
  namespace: smartdine
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: smartdine.imcc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartdine-service
            port:
              number: 80
